# Generated by Django 3.0.5 on 2020-10-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20200925_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='categories',
            field=models.ManyToManyField(related_name='post', to='blog.Category'),
        ),
    ]
