# Generated by Django 3.0.5 on 2020-10-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20201001_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='categories',
            field=models.ManyToManyField(related_name='post', to='blog.Category'),
        ),
    ]
