# Generated by Django 3.0.5 on 2020-10-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20201002_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='categories',
            field=models.ManyToManyField(related_name='post', to='blog.Category'),
        ),
    ]
