# Generated by Django 3.0.5 on 2020-07-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_photographers_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company_images',
        ),
        migrations.DeleteModel(
            name='photographers_image',
        ),
    ]
