# Generated by Django 3.0.5 on 2020-07-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20200720_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_photographer',
            old_name='upload_image',
            new_name='photographers_image',
        ),
    ]
