# Generated by Django 3.0.5 on 2020-07-20 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20200720_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_photographer',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
