# Generated by Django 3.0.5 on 2020-07-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_about_photographer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_photographer',
            name='name',
        ),
    ]
