# Generated by Django 3.0.5 on 2020-10-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20201001_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='wallpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_image', models.ImageField(upload_to='gallery/testimonial')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
