# Generated by Django 3.0.5 on 2020-10-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_wallpaper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallpaper',
            old_name='testimonial_image',
            new_name='wallpaper_image',
        ),
    ]
